/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as ParcoursRouteImport } from './routes/parcours'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as CarbonQuizResultsRouteImport } from './routes/carbon-quiz-results'
import { Route as CarbonQuizQuestionsRouteImport } from './routes/carbon-quiz-questions'
import { Route as CarbonQuizRouteImport } from './routes/carbon-quiz'
import { Route as IndexRouteImport } from './routes/index'

const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const ParcoursRoute = ParcoursRouteImport.update({
  id: '/parcours',
  path: '/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonQuizResultsRoute = CarbonQuizResultsRouteImport.update({
  id: '/carbon-quiz-results',
  path: '/carbon-quiz-results',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonQuizQuestionsRoute = CarbonQuizQuestionsRouteImport.update({
  id: '/carbon-quiz-questions',
  path: '/carbon-quiz-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonQuizRoute = CarbonQuizRouteImport.update({
  id: '/carbon-quiz',
  path: '/carbon-quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carbon-quiz': typeof CarbonQuizRoute
  '/carbon-quiz-questions': typeof CarbonQuizQuestionsRoute
  '/carbon-quiz-results': typeof CarbonQuizResultsRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/parcours': typeof ParcoursRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carbon-quiz': typeof CarbonQuizRoute
  '/carbon-quiz-questions': typeof CarbonQuizQuestionsRoute
  '/carbon-quiz-results': typeof CarbonQuizResultsRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/parcours': typeof ParcoursRoute
  '/quiz': typeof QuizRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carbon-quiz': typeof CarbonQuizRoute
  '/carbon-quiz-questions': typeof CarbonQuizQuestionsRoute
  '/carbon-quiz-results': typeof CarbonQuizResultsRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/parcours': typeof ParcoursRoute
  '/quiz': typeof QuizRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carbon-quiz'
    | '/carbon-quiz-questions'
    | '/carbon-quiz-results'
    | '/inscription'
    | '/login'
    | '/parcours'
    | '/quiz'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carbon-quiz'
    | '/carbon-quiz-questions'
    | '/carbon-quiz-results'
    | '/inscription'
    | '/login'
    | '/parcours'
    | '/quiz'
  id:
    | '__root__'
    | '/'
    | '/carbon-quiz'
    | '/carbon-quiz-questions'
    | '/carbon-quiz-results'
    | '/inscription'
    | '/login'
    | '/parcours'
    | '/quiz'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarbonQuizRoute: typeof CarbonQuizRoute
  CarbonQuizQuestionsRoute: typeof CarbonQuizQuestionsRoute
  CarbonQuizResultsRoute: typeof CarbonQuizResultsRoute
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  ParcoursRoute: typeof ParcoursRoute
  QuizRoute: typeof QuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parcours': {
      id: '/parcours'
      path: '/parcours'
      fullPath: '/parcours'
      preLoaderRoute: typeof ParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-quiz-results': {
      id: '/carbon-quiz-results'
      path: '/carbon-quiz-results'
      fullPath: '/carbon-quiz-results'
      preLoaderRoute: typeof CarbonQuizResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-quiz-questions': {
      id: '/carbon-quiz-questions'
      path: '/carbon-quiz-questions'
      fullPath: '/carbon-quiz-questions'
      preLoaderRoute: typeof CarbonQuizQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-quiz': {
      id: '/carbon-quiz'
      path: '/carbon-quiz'
      fullPath: '/carbon-quiz'
      preLoaderRoute: typeof CarbonQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarbonQuizRoute: CarbonQuizRoute,
  CarbonQuizQuestionsRoute: CarbonQuizQuestionsRoute,
  CarbonQuizResultsRoute: CarbonQuizResultsRoute,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  ParcoursRoute: ParcoursRoute,
  QuizRoute: QuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
