/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ObjectifsRouteImport } from './routes/objectifs'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as DonneesRouteImport } from './routes/donnees'
import { Route as CommunautesRouteImport } from './routes/communautes'
import { Route as CarbonQuizQuestionsRouteImport } from './routes/carbon-quiz-questions'
import { Route as ActualitesRouteImport } from './routes/actualites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonneesIndexRouteImport } from './routes/donnees.index'
import { Route as CommunautesIndexRouteImport } from './routes/communautes.index'
import { Route as OnboardingQuizRouteImport } from './routes/onboarding/quiz'
import { Route as OnboardingParcoursRouteImport } from './routes/onboarding/parcours'
import { Route as DonneesBilanOnboardingRouteImport } from './routes/donnees.bilan-onboarding'
import { Route as CommunautesRejoindreRouteImport } from './routes/communautes.rejoindre'
import { Route as CommunautesCreationRouteImport } from './routes/communautes.creation'
import { Route as CommunautesCommunityIdRouteImport } from './routes/communautes.$communityId'
import { Route as DonneesScoreIdRouteImport } from './routes/donnees.score.$id'

const ObjectifsRoute = ObjectifsRouteImport.update({
  id: '/objectifs',
  path: '/objectifs',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesRoute = DonneesRouteImport.update({
  id: '/donnees',
  path: '/donnees',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunautesRoute = CommunautesRouteImport.update({
  id: '/communautes',
  path: '/communautes',
  getParentRoute: () => rootRouteImport,
} as any)
const CarbonQuizQuestionsRoute = CarbonQuizQuestionsRouteImport.update({
  id: '/carbon-quiz-questions',
  path: '/carbon-quiz-questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ActualitesRoute = ActualitesRouteImport.update({
  id: '/actualites',
  path: '/actualites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesIndexRoute = DonneesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DonneesRoute,
} as any)
const CommunautesIndexRoute = CommunautesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CommunautesRoute,
} as any)
const OnboardingQuizRoute = OnboardingQuizRouteImport.update({
  id: '/onboarding/quiz',
  path: '/onboarding/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingParcoursRoute = OnboardingParcoursRouteImport.update({
  id: '/onboarding/parcours',
  path: '/onboarding/parcours',
  getParentRoute: () => rootRouteImport,
} as any)
const DonneesBilanOnboardingRoute = DonneesBilanOnboardingRouteImport.update({
  id: '/bilan-onboarding',
  path: '/bilan-onboarding',
  getParentRoute: () => DonneesRoute,
} as any)
const CommunautesRejoindreRoute = CommunautesRejoindreRouteImport.update({
  id: '/rejoindre',
  path: '/rejoindre',
  getParentRoute: () => CommunautesRoute,
} as any)
const CommunautesCreationRoute = CommunautesCreationRouteImport.update({
  id: '/creation',
  path: '/creation',
  getParentRoute: () => CommunautesRoute,
} as any)
const CommunautesCommunityIdRoute = CommunautesCommunityIdRouteImport.update({
  id: '/$communityId',
  path: '/$communityId',
  getParentRoute: () => CommunautesRoute,
} as any)
const DonneesScoreIdRoute = DonneesScoreIdRouteImport.update({
  id: '/score/$id',
  path: '/score/$id',
  getParentRoute: () => DonneesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/carbon-quiz-questions': typeof CarbonQuizQuestionsRoute
  '/communautes': typeof CommunautesRouteWithChildren
  '/donnees': typeof DonneesRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/objectifs': typeof ObjectifsRoute
  '/communautes/$communityId': typeof CommunautesCommunityIdRoute
  '/communautes/creation': typeof CommunautesCreationRoute
  '/communautes/rejoindre': typeof CommunautesRejoindreRoute
  '/donnees/bilan-onboarding': typeof DonneesBilanOnboardingRoute
  '/onboarding/parcours': typeof OnboardingParcoursRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/communautes/': typeof CommunautesIndexRoute
  '/donnees/': typeof DonneesIndexRoute
  '/donnees/score/$id': typeof DonneesScoreIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/carbon-quiz-questions': typeof CarbonQuizQuestionsRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/objectifs': typeof ObjectifsRoute
  '/communautes/$communityId': typeof CommunautesCommunityIdRoute
  '/communautes/creation': typeof CommunautesCreationRoute
  '/communautes/rejoindre': typeof CommunautesRejoindreRoute
  '/donnees/bilan-onboarding': typeof DonneesBilanOnboardingRoute
  '/onboarding/parcours': typeof OnboardingParcoursRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/communautes': typeof CommunautesIndexRoute
  '/donnees': typeof DonneesIndexRoute
  '/donnees/score/$id': typeof DonneesScoreIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actualites': typeof ActualitesRoute
  '/carbon-quiz-questions': typeof CarbonQuizQuestionsRoute
  '/communautes': typeof CommunautesRouteWithChildren
  '/donnees': typeof DonneesRouteWithChildren
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/objectifs': typeof ObjectifsRoute
  '/communautes/$communityId': typeof CommunautesCommunityIdRoute
  '/communautes/creation': typeof CommunautesCreationRoute
  '/communautes/rejoindre': typeof CommunautesRejoindreRoute
  '/donnees/bilan-onboarding': typeof DonneesBilanOnboardingRoute
  '/onboarding/parcours': typeof OnboardingParcoursRoute
  '/onboarding/quiz': typeof OnboardingQuizRoute
  '/communautes/': typeof CommunautesIndexRoute
  '/donnees/': typeof DonneesIndexRoute
  '/donnees/score/$id': typeof DonneesScoreIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actualites'
    | '/carbon-quiz-questions'
    | '/communautes'
    | '/donnees'
    | '/inscription'
    | '/login'
    | '/objectifs'
    | '/communautes/$communityId'
    | '/communautes/creation'
    | '/communautes/rejoindre'
    | '/donnees/bilan-onboarding'
    | '/onboarding/parcours'
    | '/onboarding/quiz'
    | '/communautes/'
    | '/donnees/'
    | '/donnees/score/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actualites'
    | '/carbon-quiz-questions'
    | '/inscription'
    | '/login'
    | '/objectifs'
    | '/communautes/$communityId'
    | '/communautes/creation'
    | '/communautes/rejoindre'
    | '/donnees/bilan-onboarding'
    | '/onboarding/parcours'
    | '/onboarding/quiz'
    | '/communautes'
    | '/donnees'
    | '/donnees/score/$id'
  id:
    | '__root__'
    | '/'
    | '/actualites'
    | '/carbon-quiz-questions'
    | '/communautes'
    | '/donnees'
    | '/inscription'
    | '/login'
    | '/objectifs'
    | '/communautes/$communityId'
    | '/communautes/creation'
    | '/communautes/rejoindre'
    | '/donnees/bilan-onboarding'
    | '/onboarding/parcours'
    | '/onboarding/quiz'
    | '/communautes/'
    | '/donnees/'
    | '/donnees/score/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActualitesRoute: typeof ActualitesRoute
  CarbonQuizQuestionsRoute: typeof CarbonQuizQuestionsRoute
  CommunautesRoute: typeof CommunautesRouteWithChildren
  DonneesRoute: typeof DonneesRouteWithChildren
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  ObjectifsRoute: typeof ObjectifsRoute
  OnboardingParcoursRoute: typeof OnboardingParcoursRoute
  OnboardingQuizRoute: typeof OnboardingQuizRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/objectifs': {
      id: '/objectifs'
      path: '/objectifs'
      fullPath: '/objectifs'
      preLoaderRoute: typeof ObjectifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees': {
      id: '/donnees'
      path: '/donnees'
      fullPath: '/donnees'
      preLoaderRoute: typeof DonneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/communautes': {
      id: '/communautes'
      path: '/communautes'
      fullPath: '/communautes'
      preLoaderRoute: typeof CommunautesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carbon-quiz-questions': {
      id: '/carbon-quiz-questions'
      path: '/carbon-quiz-questions'
      fullPath: '/carbon-quiz-questions'
      preLoaderRoute: typeof CarbonQuizQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actualites': {
      id: '/actualites'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees/': {
      id: '/donnees/'
      path: '/'
      fullPath: '/donnees/'
      preLoaderRoute: typeof DonneesIndexRouteImport
      parentRoute: typeof DonneesRoute
    }
    '/communautes/': {
      id: '/communautes/'
      path: '/'
      fullPath: '/communautes/'
      preLoaderRoute: typeof CommunautesIndexRouteImport
      parentRoute: typeof CommunautesRoute
    }
    '/onboarding/quiz': {
      id: '/onboarding/quiz'
      path: '/onboarding/quiz'
      fullPath: '/onboarding/quiz'
      preLoaderRoute: typeof OnboardingQuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/parcours': {
      id: '/onboarding/parcours'
      path: '/onboarding/parcours'
      fullPath: '/onboarding/parcours'
      preLoaderRoute: typeof OnboardingParcoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donnees/bilan-onboarding': {
      id: '/donnees/bilan-onboarding'
      path: '/bilan-onboarding'
      fullPath: '/donnees/bilan-onboarding'
      preLoaderRoute: typeof DonneesBilanOnboardingRouteImport
      parentRoute: typeof DonneesRoute
    }
    '/communautes/rejoindre': {
      id: '/communautes/rejoindre'
      path: '/rejoindre'
      fullPath: '/communautes/rejoindre'
      preLoaderRoute: typeof CommunautesRejoindreRouteImport
      parentRoute: typeof CommunautesRoute
    }
    '/communautes/creation': {
      id: '/communautes/creation'
      path: '/creation'
      fullPath: '/communautes/creation'
      preLoaderRoute: typeof CommunautesCreationRouteImport
      parentRoute: typeof CommunautesRoute
    }
    '/communautes/$communityId': {
      id: '/communautes/$communityId'
      path: '/$communityId'
      fullPath: '/communautes/$communityId'
      preLoaderRoute: typeof CommunautesCommunityIdRouteImport
      parentRoute: typeof CommunautesRoute
    }
    '/donnees/score/$id': {
      id: '/donnees/score/$id'
      path: '/score/$id'
      fullPath: '/donnees/score/$id'
      preLoaderRoute: typeof DonneesScoreIdRouteImport
      parentRoute: typeof DonneesRoute
    }
  }
}

interface CommunautesRouteChildren {
  CommunautesCommunityIdRoute: typeof CommunautesCommunityIdRoute
  CommunautesCreationRoute: typeof CommunautesCreationRoute
  CommunautesRejoindreRoute: typeof CommunautesRejoindreRoute
  CommunautesIndexRoute: typeof CommunautesIndexRoute
}

const CommunautesRouteChildren: CommunautesRouteChildren = {
  CommunautesCommunityIdRoute: CommunautesCommunityIdRoute,
  CommunautesCreationRoute: CommunautesCreationRoute,
  CommunautesRejoindreRoute: CommunautesRejoindreRoute,
  CommunautesIndexRoute: CommunautesIndexRoute,
}

const CommunautesRouteWithChildren = CommunautesRoute._addFileChildren(
  CommunautesRouteChildren,
)

interface DonneesRouteChildren {
  DonneesBilanOnboardingRoute: typeof DonneesBilanOnboardingRoute
  DonneesIndexRoute: typeof DonneesIndexRoute
  DonneesScoreIdRoute: typeof DonneesScoreIdRoute
}

const DonneesRouteChildren: DonneesRouteChildren = {
  DonneesBilanOnboardingRoute: DonneesBilanOnboardingRoute,
  DonneesIndexRoute: DonneesIndexRoute,
  DonneesScoreIdRoute: DonneesScoreIdRoute,
}

const DonneesRouteWithChildren =
  DonneesRoute._addFileChildren(DonneesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActualitesRoute: ActualitesRoute,
  CarbonQuizQuestionsRoute: CarbonQuizQuestionsRoute,
  CommunautesRoute: CommunautesRouteWithChildren,
  DonneesRoute: DonneesRouteWithChildren,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  ObjectifsRoute: ObjectifsRoute,
  OnboardingParcoursRoute: OnboardingParcoursRoute,
  OnboardingQuizRoute: OnboardingQuizRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
